CREATE TABLE IF NOT EXISTS BOOK (
    ID TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    AUTHOR TEXT NOT NULL,
    document jsonb NOT NULL,
    PRIMARY KEY(ID)
);
CREATE INDEX BOOK_ID_IDX ON BOOK (ID);
CREATE INDEX BOOK_TITLE_IDX ON BOOK (TITLE);
CREATE INDEX BOOK_AUTHOR_IDX ON BOOK (AUTHOR);